export const tokenFactoryAbi = [
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'symbol', type: 'string' },
      { internalType: 'uint256', name: 'supply', type: 'uint256' },
      { internalType: 'uint8', name: 'decimals', type: 'uint8' },
      { internalType: 'string', name: 'iconUrl', type: 'string' },
      { internalType: 'string', name: 'anchorPrice', type: 'string' },
    ],
    name: 'createToken',
    outputs: [{ internalType: 'address', name: 'tokenAddress', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'creator', type: 'address' },
      { indexed: true, internalType: 'address', name: 'tokenAddress', type: 'address' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      { indexed: false, internalType: 'string', name: 'symbol', type: 'string' },
      { indexed: false, internalType: 'string', name: 'iconUrl', type: 'string' },
      { indexed: false, internalType: 'string', name: 'anchorPrice', type: 'string' },
    ],
    name: 'TokenCreated',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'symbol', type: 'string' },
      { internalType: 'uint256', name: 'supply', type: 'uint256' },
      { internalType: 'uint8', name: 'decimals', type: 'uint8' },
      { internalType: 'string', name: 'iconUrl', type: 'string' },
      { internalType: 'string', name: 'anchorPrice', type: 'string' },
      { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
    ],
    name: 'createTokenVanity',
    outputs: [{ internalType: 'address', name: 'tokenAddress', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'symbol', type: 'string' },
      { internalType: 'uint256', name: 'supply', type: 'uint256' },
      { internalType: 'uint8', name: 'decimals', type: 'uint8' },
      { internalType: 'string', name: 'iconUrl', type: 'string' },
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'bytes32', name: 'salt', type: 'bytes32' },
    ],
    name: 'predictTokenAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'symbol', type: 'string' },
      { internalType: 'uint256', name: 'supply', type: 'uint256' },
      { internalType: 'uint8', name: 'decimals', type: 'uint8' },
      { internalType: 'string', name: 'iconUrl', type: 'string' },
      { internalType: 'address', name: 'owner', type: 'address' },
    ],
    name: 'getInitCodeHash',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'pure',
    type: 'function',
  },
] as const;
